version: "3.9"
services:
  web:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "webdata:/usr/share/nginx/html"
    networks:
      - "frontend"

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - "backend"

volumes:
  webdata:
  dbdata:

networks:
  frontend:
  backend:

